### ISSUE TITLE
Updating node modules

### ISSUE THREAD

**Issue by AngelOnFira** [edwinwebb/three-seed#20]
I'm not sure the state of this repo, as there haven't been any changes to master in over a year. Running `npm install` yielded 163 vulnerabilities. Running `npm audit fix` seems to resolve all the issues, but I'm not familiar enough with node to know that it fixes everything properly.

Just wondering if it's worth making a PR for this repo, or if I should just keep it on my fork.

**Comment by edwinwebb** [comment]
closed by #22
